#!/bin/bash

PID=$(pgrep -f 'ssh -p 22 pocketbase')

if [ -z "$PID" ]; then
  echo "No Connections to VPS"
else
  echo "Stopping Connections to VPS (PID: $PID)..."
  kill -9 $PID
  echo "Connections stopped."
fi
